; EXPORT.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : Byte-count as Constant.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 1
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

 SECTION "Tiles", ROMX

; Start of tile array.
TileLabel::
DB $FF,$81,$C3,$7E,$A5,$7E,$99,$7E
DB $99,$7E,$A5,$7E,$C3,$7E,$FF,$81
DB $00,$C0,$00,$40,$00,$40,$00,$60
DB $00,$30,$00,$18,$00,$0E,$00,$03

; End of EXPORT.Z80
